version: '3'
tasks:
  run:application:
    cmds:
      - go run ./application/src/main.go
  run:consumer:
    cmds:
      - go run ./consumer/src/main.go
  start:
    cmds:
      - docker-compose up -d --build
  down:
    cmds:
      - docker-compose down
  test:load:
    cmds:
      - 'hey -n 100000 -c 50 -m POST -H "Content-Type: application/json" -D ./request_body.txt http://localhost:8000/save'